[build]
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY,VITE_SUPABASE_ANON_KEY" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers - applied to all HTML pages only
[[headers]]
  for = "/*.html"
  [headers.values]
    # Critical security header - prevents MIME type sniffing
    X-Content-Type-Options = "nosniff"
    # Use modern CSP with frame-ancestors instead of deprecated X-Frame-Options
    Content-Security-Policy = "frame-ancestors 'self'"
    # Additional security headers for HTML pages only
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers for root HTML (index.html)
[[headers]]
  for = "/"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'self'"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers for static assets (images, fonts, etc.) - minimal headers
[[headers]]
  for = "/*.png"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.jpg"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.jpeg"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.svg"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/assets/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for API routes and functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Scheduled function for Voice of San Diego events (daily at 10 AM UTC)
[[schedule]]
  expression = "0 10 * * *"
  function = "fetch-vosd-events"

# Scheduled function for KPBS events (daily at 10 AM Pacific Time)
# Note: Use "0 17 * * *" for PST (Nov-Mar) or "0 18 * * *" for PDT (Mar-Nov)
[[schedule]]
  expression = "0 17 * * *"
  function = "fetch-kpbs-events"