[build]
  command = "npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY,VITE_SUPABASE_ANON_KEY" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Scheduled function for Voice of San Diego events (daily at 10 AM)
[[schedule]]
  expression = "0 10 * * *"
  function = "fetch-vosd-events"